Repository zowe/zowe-common-c, pull requests merged in 2021-01, with the labels that each got.

#183 Make zss storage API
  c/dataservice.c
  c/storage.c
  c/storage_mem.c
  h/dataservice.h
  h/storage.h
Labels: HA, enhancement

#190 Make group lookup function for user
  c/zosaccounts.c
  h/zosaccounts.h
Labels: enhancement

#195 Fix an implicit declaration
  c/stcbase.c
Labels: bug
